api.insecure=true
providers.docker=true
acme.acmeLogging = true
[log]
  filePath = "/var/log/traefik/traefik.log"
  level = "DEBUG"
[entrypoints]
  web.address=":80"
  websecure.address=":443"
  emqx-admin.address=":18083"
  mqtt.address=":1883"
  ws.address=":8083"
  minio-api.address=":9000"
[certificatesresolvers.dns.acme]
  dnschallenge.provider = "cloudflare"
  dnschallenge.resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
  storage = "/letsencrypt/acme.json"
#  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
